import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./css/index.css";
import 'aos/dist/aos.css';
import React from "react";
import {Analytics} from "@vercel/analytics/react";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">

      <body className={inter.className}>
      <Analytics/>
      <main id="maincontent">
        {children}
      </main>
      </body>
      </html>
  );
}